"""
report_generator.py
--------------------
Builds downloadable PDF reports (Data Quality, Analytics, Business Insights)
using ReportLab, and helpers to export cleaned data as CSV/Excel bytes.
"""

import io
from datetime import datetime

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)

PRIMARY_COLOR = colors.HexColor("#6953F0")
SECONDARY_COLOR = colors.HexColor("#161325")
LIGHT_BG = colors.HexColor("#F2F0FC")


def _get_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="ReportTitle", fontSize=22, leading=26, textColor=PRIMARY_COLOR,
        spaceAfter=6, fontName="Helvetica-Bold"
    ))
    styles.add(ParagraphStyle(
        name="ReportSubtitle", fontSize=11, textColor=colors.grey, spaceAfter=20
    ))
    styles.add(ParagraphStyle(
        name="SectionHeader", fontSize=14, textColor=SECONDARY_COLOR,
        spaceBefore=16, spaceAfter=8, fontName="Helvetica-Bold"
    ))
    styles.add(ParagraphStyle(
        name="BodyTextCustom", fontSize=10, leading=15, spaceAfter=8
    ))
    return styles


def _markdown_bold_to_html(text):
    """Convert simple **bold** markdown into ReportLab-compatible <b> tags."""
    parts = text.split("**")
    out = ""
    for i, part in enumerate(parts):
        out += f"<b>{part}</b>" if i % 2 == 1 else part
    return out


def _header_footer(canvas, doc, title):
    canvas.saveState()
    canvas.setFillColor(SECONDARY_COLOR)
    canvas.rect(0, letter[1] - 0.6 * inch, letter[0], 0.6 * inch, fill=True, stroke=False)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawString(0.5 * inch, letter[1] - 0.4 * inch, title)
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(
        letter[0] - 0.5 * inch, letter[1] - 0.4 * inch,
        datetime.now().strftime("%B %d, %Y")
    )
    canvas.setFillColor(colors.grey)
    canvas.setFont("Helvetica", 8)
    canvas.drawCentredString(letter[0] / 2, 0.4 * inch, f"Page {doc.page} | Generated by AnalytixAI")
    canvas.restoreState()


def _df_to_table(df, max_rows=20):
    df_display = df.head(max_rows).copy()
    df_display = df_display.astype(str)
    data = [list(df_display.columns)] + df_display.values.tolist()
    table = Table(data, repeatRows=1, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_COLOR),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return table


def generate_data_quality_pdf(file_name, basic_info, quality_score, issues, missing_report):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                             topMargin=0.9 * inch, bottomMargin=0.7 * inch,
                             leftMargin=0.6 * inch, rightMargin=0.6 * inch)
    styles = _get_styles()
    elements = []

    elements.append(Paragraph("Data Quality Report", styles["ReportTitle"]))
    elements.append(Paragraph(f"Source file: {file_name}", styles["ReportSubtitle"]))

    elements.append(Paragraph("Dataset Overview", styles["SectionHeader"]))
    overview_data = [
        ["Metric", "Value"],
        ["Total Rows", f"{basic_info['rows']:,}"],
        ["Total Columns", f"{basic_info['columns']:,}"],
        ["Memory Usage (MB)", f"{basic_info['memory_usage_mb']}"],
        ["Overall Quality Score", f"{quality_score['overall_score']} / 100"],
    ]
    t = Table(overview_data, hAlign="LEFT", colWidths=[200, 200])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_COLOR),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    elements.append(t)

    elements.append(Paragraph("Quality Score Breakdown", styles["SectionHeader"]))
    breakdown_data = [
        ["Dimension", "Score (%)"],
        ["Completeness", f"{quality_score['completeness']}"],
        ["Uniqueness", f"{quality_score['uniqueness']}"],
        ["Validity", f"{quality_score['validity']}"],
        ["Consistency", f"{quality_score['consistency']}"],
    ]
    t2 = Table(breakdown_data, hAlign="LEFT", colWidths=[200, 200])
    t2.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), SECONDARY_COLOR),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    elements.append(t2)

    elements.append(Paragraph("Identified Issues", styles["SectionHeader"]))
    for issue in issues:
        elements.append(Paragraph(f"• {_markdown_bold_to_html(issue)}", styles["BodyTextCustom"]))

    if not missing_report.empty:
        elements.append(Paragraph("Missing Values by Column", styles["SectionHeader"]))
        elements.append(_df_to_table(missing_report))

    doc.build(
        elements,
        onFirstPage=lambda c, d: _header_footer(c, d, "Data Quality Report"),
        onLaterPages=lambda c, d: _header_footer(c, d, "Data Quality Report"),
    )
    buffer.seek(0)
    return buffer


def generate_analytics_pdf(file_name, basic_info, stat_summary, correlation_df):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                             topMargin=0.9 * inch, bottomMargin=0.7 * inch,
                             leftMargin=0.6 * inch, rightMargin=0.6 * inch)
    styles = _get_styles()
    elements = []

    elements.append(Paragraph("Analytics Report", styles["ReportTitle"]))
    elements.append(Paragraph(f"Source file: {file_name}", styles["ReportSubtitle"]))
    elements.append(Paragraph(
        f"Dataset: {basic_info['rows']:,} rows × {basic_info['columns']} columns",
        styles["BodyTextCustom"]
    ))

    if stat_summary is not None and not stat_summary.empty:
        elements.append(Paragraph("Statistical Summary", styles["SectionHeader"]))
        stat_display = stat_summary.reset_index().rename(columns={"index": "Column"})
        elements.append(_df_to_table(stat_display, max_rows=15))

    if correlation_df is not None and not correlation_df.empty:
        elements.append(PageBreak())
        elements.append(Paragraph("Correlation Matrix", styles["SectionHeader"]))
        corr_display = correlation_df.reset_index().rename(columns={"index": "Column"})
        elements.append(_df_to_table(corr_display, max_rows=15))

    doc.build(
        elements,
        onFirstPage=lambda c, d: _header_footer(c, d, "Analytics Report"),
        onLaterPages=lambda c, d: _header_footer(c, d, "Analytics Report"),
    )
    buffer.seek(0)
    return buffer


def generate_insights_pdf(file_name, exec_summary, key_findings, recommendations):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                             topMargin=0.9 * inch, bottomMargin=0.7 * inch,
                             leftMargin=0.6 * inch, rightMargin=0.6 * inch)
    styles = _get_styles()
    elements = []

    elements.append(Paragraph("Business Insights Report", styles["ReportTitle"]))
    elements.append(Paragraph(f"Source file: {file_name}", styles["ReportSubtitle"]))

    elements.append(Paragraph("Executive Summary", styles["SectionHeader"]))
    elements.append(Paragraph(_markdown_bold_to_html(exec_summary), styles["BodyTextCustom"]))

    elements.append(Paragraph("Key Findings", styles["SectionHeader"]))
    for finding in key_findings:
        elements.append(Paragraph(f"• {_markdown_bold_to_html(finding)}", styles["BodyTextCustom"]))

    elements.append(Paragraph("Recommendations", styles["SectionHeader"]))
    for rec in recommendations:
        elements.append(Paragraph(f"• {_markdown_bold_to_html(rec)}", styles["BodyTextCustom"]))

    doc.build(
        elements,
        onFirstPage=lambda c, d: _header_footer(c, d, "Business Insights Report"),
        onLaterPages=lambda c, d: _header_footer(c, d, "Business Insights Report"),
    )
    buffer.seek(0)
    return buffer


# ---------------------------------------------------------------------------
# Data export helpers
# ---------------------------------------------------------------------------

def df_to_csv_bytes(df):
    return df.to_csv(index=False).encode("utf-8")


def df_to_excel_bytes(df):
    buffer = io.BytesIO()
    with pd.ExcelWriter(buffer, engine="xlsxwriter") as writer:
        df.to_excel(writer, index=False, sheet_name="Cleaned Data")
    buffer.seek(0)
    return buffer.getvalue()
